# config.py
# Race Constraints

TOTAL_LAPS = 52
SIM_TIMESTEP = 0.05

# Track

TRACK_LENGTH = 5891
TRACK_WIDTH = 12
NUM_SEGMENTS = 300
GRAVEL_WIDTH = 5.0
SEVERE_OFFTRACK_DISTANCE = 5.0

# Physics

MAX_SPEED = 92.0
MIN_CORNER_SPEED = 18.0
ACCEL_RATE = 12.0
BRAKE_RATE = 28.0
MAX_STEERING_ANGLE = 0.8
GRAVITY = 9.81
CORNERING_G_FACTOR = 3.5

# Fuel Model
FUEL_START = 110.0
FUEL_DNF_THRESHOLD = 1.8
FUEL_BASE_CONSUMPTION_PER_METER = 0.000295
FUEL_THROTTLE_FACTOR = 0.3
FUEL_WEIGHT_TIME_COST = 0.03
FUEL_WEIGHT_TIME_PER_METER = 5.09e-6

#Tyre Model
OFFTRACK_WEAR_PER_EXCURSION = 2.0
OFFTRACK_WEAR_PER_SECOND = 0.5
MAX_TYRE_WEAR = 100.0

TYRE_BASE_WEAR = {
    "Soft": 1.8,
    "Medium": 1.1,
    "Hard": 0.7,
    "Wet": 1.3,
}


TYRE_STRESS_MIN = 1.0
TYRE_STRESS_MAX = 1.5

TYRE_MISMATCH_FACTOR = {
    ("Slicks", "Wet"): 3.0,
    ("Slicks", "Drying"): 1.5,
    ("Wets", "Dry"): 2.5,
    ("Wets", "Drying"): 1.5,
}

TYRE_SPEED_FACTOR = {
    "Soft": 1.00,
    "Medium": 0.97,
    "Hard": 0.94,
    "Wet": 0.88,
}

SLICKS = ("Soft", "Medium", "Hard")
WETS = ("Wet",)

# Grip Model
GRIP_MATRIX = {
    "Dry": {"Slicks": 1.00, "Wets": 0.55},
    "Drying": {"Slicks": 0.65, "Wets": 0.75},
    "Wet": {"Slicks": 0.35, "Wets": 0.85},
}

GRIP_WEAR_PENALTY = 0.4
GRIP_MIN = 0.10

# Pit Stop

PIT_LANE_SPEED_LIMIT = 22.0
PIT_LANE_LENGTH = 400.0
PIT_TYRE_CHANGE_TIME = 2.5
MIN_PIT_STOPS = 1
DRY_REQUIRES_TWO_COMPOUNDS = True
WET_REQUIRES_WET_COMPOUND = True

# Off Track Penalties
OFFTRACK_FREE_EXCURSIONS = 4
OFFTRACK_TIME_PENALTY = 5.0
OFFTRACK_GRIP_PENALTY = 0.5
OFFTRACK_GRIP_RECOVERY_TIME = 1.0

# Weather

WEATHER_SCENARIOS = [
    "FullDry",
    "FullWet",
    "DryToWet",
    "WetToDry",
    "Mixed",
]

WEATHER_TRANSITION_LAP_MIN = 10
WEATHER_TRANSITION_LAP_MAX = 40
WEATHER_TRANSITION_DURATION_LAPS = 10

#Reinforcement Learning

RL_STEERING_BINS = [-1.0, -0.5, 0.0, 0.5, 1.0]
RL_THROTTLE_BINS = [-1.0, -0.5, 0.0, 0.5, 1.0]
RL_PIT_BINS = [0, 1]
RL_COMPOUND_BINS = ["Soft", "Medium", "Hard", "Wet"]

RL_LOOKAHEAD_TIMES = [0.5, 1.0, 2.0, 3.0, 5.0]
RL_STATE_DIM = 19

PPO_LEARNING_RATE = 3e-4
PPO_N_STEPS = 2048
PPO_BATCH_SIZE = 256
PPO_N_EPOCHS = 10
PPO_GAMMA = 0.99
PPO_GAE_LAMBDA = 0.95
PPO_CLIP_RANGE = 0.2
PPO_ENT_COEF = 0.01
PPO_VF_COEF = 0.5
PPO_MAX_GRAD_NORM = 0.5

TRAIN_TIMESTEPS_PHASE1 = 4_000_000
TRAIN_TIMESTEPS_PHASE2 = 2_000_000
TRAIN_NUM_PARALLEL_ENVS = 8

#Reward Shaping
REWARD_TIME_COST_PER_SECOND = -1.0
REWARD_PROGRESS_PER_METER = 0.1
REWARD_LAP_BASE = 200.0
REWARD_OFFTRACK_PER_SEC = -5.0
REWARD_WEAR_PER_PERCENT = -0.02
REWARD_DNF = -1000.0
REWARD_OUT_OF_FUEL_EXTRA = -2000.0
REWARD_FINISH_BASE = 2000.0
REWARD_FUEL_REMAINING_PER_KG = 5.0
REWARD_FUEL_USED_PER_KG = -10.0

EXPERIMENT_RUNS_PER_CONDITION = 15
EXPERIMENT_AGENTS = ["RuleBased", "Utility", "RL"]
EXPERIMENT_CONDITIONS = WEATHER_SCENARIOS

#Metrics

METRICS = [
    "total_race_time",
    "mean_lap_time",
    "lap_time_variance",
    "track_violations",
    "tyre_efficiency",
    "dnf",
    "pit_stops",
    "fuel_remaining_at_end",
]

# Statistics
SIGNIFICANCE_LEVEL = 0.05
USE_BONFERRONI = True

# Rule Based Agent
RULE_BASED_DRY_START_TYRE = "Medium"
RULE_BASED_DRY_PIT_TYRE = "Hard"
RULE_BASED_WET_TYRE = "Wet"
RULE_BASED_PIT_LAP = 26
RULE_BASED_WEAR_THRESHOLD = 70.0

# Utility Agent

UTILITY_PIT_TIME_COST = 21.0
UTILITY_GRIP_THRESHOLD_FOR_PITTING = 0.50
UTILITY_THROTTLE_GRIP_SCALING = 0.0
UTILITY_WEAR_SCALING = 0.0

BASE_SEED = 42
